name: regulator
description: Regulate your daily activities.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+10
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  rxdart: ^0.27.5
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
